# For more information please visit https://github.com/attozk/hathoora/wiki/Configuration#define-applications-or-websites-being-supported

# Define application or website that are being supported.
app:
    # admin site
    admin: 
        pattern: /admin(|/)
        directory: sample
    # Default site
    site: 
        default: true
        directory: sample