#imports:
#    - { resource: config.yml }

#translation:
#    # when enabled adds 'translation' service
#    enabled: 1 

logger:
    profiling: 1
    logging: 
        enabled: 1
        level: DEBUG
    webprofiler: 
        enabled: 1
        content_type: 'text/html'
        skipOnPostParam: 'pajax'
        skipOnGetParam: 'pajax'

#assets:
#    version: v20130428.2
#    urls: 
#        http: 
#        https: 

#template:
#    engine:
#        class: Stuob
#        Smarty:
#            caching: 1
#            cache_lifetime: 30
#            cache_dir: ''
#            compile_dir: ''
#            force_compile: 0
#            compile_check: 1

#database:
#    default: mysql://user@host:3306/dbname
#    db2: mysql://user@host:3306/dbname


#cache:
#    debug: 1
#    pools:
#        common: { driver: 'memcache', servers: [{host: host, port: 11211}]}
#        commonRedis: { driver: 'redis', servers: [{host: host, port: 6379}]}

#facebook:
#    app_id: 
#    secret: 

#google:
#    analytics:
#        account: 

#services:
#; hathoora cache service
#    cache:
#        class: \hathoora\cache\cache
#        calls: 
#            setContainer: [ @container@ ]
#        type: static

#; cache service for sites
#    cache.site:
#        factory_service: @cache@
#        factory_method: pool
#        factory_method_args: [ "common" ]        

#; cache service dashboard
#    cache.dashboard:
#        factory_service: @cache@
#        factory_method: pool
#        factory_method_args: [ "common" ]
                    
        
#listeners:
#    event.action:
#        observer:
#                class: NAMESPACE
#                method: method